### ISSUE TITLE
Share result image CANN'T show on page

### ISSUE THREAD

**Issue by wx2020** [adolfintel/speedtest#681]
## Description
Share result image CANN'T show on page. The image resource appears to be corrupted.

![image](https://github.com/user-attachments/assets/8be6a574-070f-475c-9ff9-163ef1216a1b)

## Docker  Compose file:
```
  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    environment:
      - MODE=standalone
      - TITLE=Speedtest by wx2020
      - WEBPORT=5001
      - TELEMETRY=true
      - ENABLE_ID_OBFUSCATION=true
      - DB_TYPE=sqlite
      - PASSWORD=tCEqt9T7MGGodX
      - EMAIL=example.com
      - IPINFO_APIKEY=xxxxxxxx
      - DISTANCE=km
      - TZ=Asia/Shanghai
    volumes:
      - ./config/speedtest/servers.json:/servers.json
      - ./config/speedtest/database:/database
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: 1m

```

## Nginx Proxy Server:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    http3 on;
    server_name speed.example.com;
    access_log /var/log/nginx/speed.example.com.log;
    error_log /var/log/nginx/speed.example.com.log;
    ssl_certificate /etc/cert/fullchain.cer;
    ssl_certificate_key /etc/cert/example.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_timeout 8h;
    ssl_session_cache shared:SSL:20m;
    ssl_session_tickets on;
    add_header Strict-Transport-Security "max-age=31536000" always;
    ssl_trusted_certificate /etc/cert/fullchain.cer;
    ssl_stapling on;
    ssl_stapling_verify on;


    location / {
        client_max_body_size 0;
        client_body_buffer_size 512k;
        client_body_timeout 30s;
        proxy_read_timeout 30s;
        proxy_send_timeout 30s;
        proxy_request_buffering off;
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_pass http://localhost:5001;
    }

}
```
What could be the reason?
Please help me.
